### ISSUE TITLE
[Info] device /dev/kvm not found

### ISSUE THREAD

**Issue by corasaniti** [hectorm/docker-qemu-win2000#10]
Hi to use your images thath using --device /dev/kvm in virtualbox what should i do.
Because in my virtualbox  Debian I can't find the --device /dev/kvm
Thanks in advance

**Comment by hectorm** [comment]
I think it is not possible to use KVM in VirtualBox, so you will have to remove the `--device /dev/kvm` option, but the emulation will be painfully slow.
