### ISSUE TITLE
docker: Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory.

### ISSUE THREAD

**Issue by wuxiongwei** [hectorm/docker-qemu-win2000#3]
pull is ok
run is wrong
and got this error message 

docker: Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory.

My OS is macOS Big Sur 
and 
docer  desktop version is  4.2.0
docker version is 20.10.10

**Comment by emengweb** [comment]
just delete "-/dev/kvm" and run it work will on my Ubuntu 18 VPS :)

**Comment by hectorm** [comment]
As @emengweb has commented, it is not possible to use KVM on macOS, so you should remove the `--device` option from the command.
