### ISSUE TITLE
Loading container goes into endless loop

### ISSUE THREAD

**Issue by andersonm66** [hectorm/docker-qemu-win2000#4]
Logs display loops the following message at 94% cpu and 69 degrees celsius. i left it run at this for 4 hours then killed it.

Current thread 0xb6f32460 (most recent call first):
<no Python frame>
Could not find child 5679 -- ignoring
Could not find child 5677 -- ignoring
Registered MSG_REQ_POOL_USAGE
Could not find child 5680 -- ignoring
Registered MSG_REQ_POOL_USAGE
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

**Comment by hectorm** [comment]
Hi, could you please tell me your operating system and the Docker command you are using to run the container?

**Comment by andersonm66** [comment]
Raspberry Pi 4 4Gb (tried also with 8)
Raspbian 32bit
Portainer with Docker

{
    "AppArmorProfile": "",
    "Args": [
        "--",
        "/usr/local/bin/container-init"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": [
            "/usr/bin/tini",
            "--",
            "/usr/local/bin/container-init"
        ],
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "VM_CPU=2",
            "VM_RAM=512M",
            "VM_KEYBOARD=en-us",
            "VM_NET_GUESTFWD_OPTIONS=guestfwd=tcp:10.0.2.254:445-cmd:nc 127.0.0.1 445",
            "VM_NET_HOSTFWD_OPTIONS=hostfwd=tcp::2323-:23,hostfwd=tcp::5151-:51,hostfwd=tcp::3389-:3389",
            "VM_NET_EXTRA_OPTIONS=",
            "VM_KVM=true",
            "SVDIR=/etc/service/"
        ],
        "ExposedPorts": {
            "3389/tcp": {},
            "5900/tcp": {},
            "6080/tcp": {}
        },
        "Hostname": "fdb38efeffd0",
        "Image": "hectormolinero/qemu-win2000:latest",
        "Labels": {},
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/mnt": {}
        },
        "WorkingDir": ""
    },
    "Created": "2021-12-07T01:05:33.106550877Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/b1d7bbbe8ee03b6fef625e93be9e53fbd7450de9329984d1cfe43a2d09a096af-init/diff:/var/lib/docker/overlay2/da181b4e238d826459e98f4cd41279f2dce8c9eb504fdaf8fb42f7bdc6aa5fb4/diff:/var/lib/docker/overlay2/c5c34d5cc14a9eaf16485cde98f1e27a4848a25301c9bfbe5a294cfae2d11d49/diff:/var/lib/docker/overlay2/3bcbc00e6db4124bb0b4289ef3d7fa0007f50f7edb04aa5e35ea4f5d952503d5/diff:/var/lib/docker/overlay2/34548e1a3e2a355aa5a4664b78fbfe60b2d3a42e6ed9aa707fe8d3ad30bc8c9d/diff:/var/lib/docker/overlay2/700465fe8d2226bffc50ad8aacd3384ed7d65da1f1481ad953d29d5d8a740fdf/diff:/var/lib/docker/overlay2/f6ad4e3a0368025c3bfed4be41df16cd4ce590871bddaa15eae0269e8fcba440/diff:/var/lib/docker/overlay2/fe2209ad4db28dd644c6c34cca63cc25ee9970a24c085611e95b4e82a2a6913d/diff:/var/lib/docker/overlay2/355a954bb74d0b413a8e24f94e9cd55d92dc4c6062fe1a620c3b9481e4166485/diff:/var/lib/docker/overlay2/2c7b37ed37c10e57c4fc4ed322919ad64863a20db13d2d38b26f6b2455455d1c/diff:/var/lib/docker/overlay2/d21d4654a2c6de722d366ffc389a8b7a112cc9cca0fbcd00104aaf04a8d2d759/diff:/var/lib/docker/overlay2/1d7380c83597e7085e76835532fa18dfc2076cfe2f1082683428902a170e3f7a/diff:/var/lib/docker/overlay2/e91a544b5b316c0251b83ab596d8d8331c09a140c21b9d5619db4d5c97f592f5/diff:/var/lib/docker/overlay2/f3ea229d49ff198c6c91f96a16f4dbe25c563f570db4d62d4352e19786018780/diff:/var/lib/docker/overlay2/0bd4073f80e1d83e25bba0770a0770ba9bfada1ecadd3c3593ff09b88b8a4744/diff:/var/lib/docker/overlay2/d8883c06960ce8673e0441b18361073eb63210cd136fe55adcac69f0b08af2f8/diff:/var/lib/docker/overlay2/d7914deb8d90cd1bd9876ca1da8d1d6963215bee252345cecd8b69f6cff36c63/diff",
            "MergedDir": "/var/lib/docker/overlay2/b1d7bbbe8ee03b6fef625e93be9e53fbd7450de9329984d1cfe43a2d09a096af/merged",
            "UpperDir": "/var/lib/docker/overlay2/b1d7bbbe8ee03b6fef625e93be9e53fbd7450de9329984d1cfe43a2d09a096af/diff",
            "WorkDir": "/var/lib/docker/overlay2/b1d7bbbe8ee03b6fef625e93be9e53fbd7450de9329984d1cfe43a2d09a096af/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/portainer/Files/AppData/Config/Win2000/zdrive:/mnt"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": null,
        "CapDrop": null,
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "host",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": null,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "bridge",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "3389/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "3389"
                }
            ],
            "5900/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "5900"
                }
            ],
            "6080/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "6080"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "unless-stopped"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/fdb38efeffd03af4dada8351f9d193e75e864f6e4a515248cce31d5465b4e327/hostname",
    "HostsPath": "/var/lib/docker/containers/fdb38efeffd03af4dada8351f9d193e75e864f6e4a515248cce31d5465b4e327/hosts",
    "Id": "fdb38efeffd03af4dada8351f9d193e75e864f6e4a515248cce31d5465b4e327",
    "Image": "sha256:534d72946888ead7924e2e9e5a773bde3f631d872f6305ea7fc0bffd4a7e653f",
    "LogPath": "/var/lib/docker/containers/fdb38efeffd03af4dada8351f9d193e75e864f6e4a515248cce31d5465b4e327/fdb38efeffd03af4dada8351f9d193e75e864f6e4a515248cce31d5465b4e327-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/mnt",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/portainer/Files/AppData/Config/Win2000/zdrive",
            "Type": "bind"
        }
    ],
    "Name": "/win2000",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "bridge": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "",
                "Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": null,
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "",
                "NetworkID": "7ac9b3ea16a731b5fa8e7ccef8d09665eefccfcca39d29ad80ed9d187c9c7a41"
            }
        },
        "Ports": {},
        "SandboxID": "014c0ee4f40143fe3a1df681072e1fbcb18441a198db22ddb60c22b1132f0ec8",
        "SandboxKey": "/var/run/docker/netns/014c0ee4f401",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/usr/bin/tini",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 14,
            "ResourceId": "fdb38efeffd03af4dada8351f9d193e75e864f6e4a515248cce31d5465b4e327",
            "SubResourceIds": [],
            "Type": 1,
            "UserAccesses": [],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": true,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/fdb38efeffd03af4dada8351f9d193e75e864f6e4a515248cce31d5465b4e327/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 143,
        "FinishedAt": "2021-12-07T23:07:55.661527689Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 0,
        "Restarting": false,
        "Running": false,
        "StartedAt": "2021-12-07T22:56:59.241937051Z",
        "Status": "exited"
    }
}

**Comment by hectorm** [comment]
It seems that you have encountered the moby/moby#40734 bug, which has been unresolved for some time.

Ideally, on your system you should use a 64 bit kernel and run the image version for arm64 architectures.

But if you don't want to make any changes to your system, another option is to run the image in privileged mode, but keep in mind that this disables the security measures of the container, but since Windows 2000 is in a VM, it doesn't open up the attack surface too much.

I tested the following command on a Raspberry Pi 4 8 GB with Raspberry Pi OS 64 bit and it worked without problems after adding the `--privileged` option, without it I suffered the same error as you.
```sh
docker run --detach --name qemu-win2000 --publish 6080:6080/tcp --privileged --env VM_KVM=false docker.io/hectormolinero/qemu-win2000:latest-arm32v7
```

Could you confirm if this solves your error?

**Comment by andersonm66** [comment]
Thanks that did the trick....
