### ISSUE TITLE
Samba mount fails - wrong IP

### ISSUE THREAD

**Issue by mkst** [hectorm/docker-qemu-win2000#7]
Hello hello! Firstly, awesome project - am looking into this as an alternative to wine... However I'm hitting an issue:

![image](https://user-images.githubusercontent.com/22226349/174370235-d6f63980-2691-4d2f-a569-6ed66ef53db0.png)

I don't know how the IP (10.0.0.254) is being [chosen](https://github.com/hectorm/docker-qemu-win2000/blob/85b93515749cd42510e348b270f94df7c541b4fa/data/iso/I386/WINNT-GUIRUNONCE.BAT#L40).

`ifconfig` from within the container:
```
root@5bc29bb97d71:/# root@5bc29bb97d71:/# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.2  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ac:11:00:02  txqueuelen 0  (Ethernet)
        RX packets 1247  bytes 128244 (128.2 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1081  bytes 122804 (122.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 18  bytes 984 (984.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 984 (984.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

`ipconfig` from within the Windows 2000 instance:
```
C:\Documents and Settings\Administrator>ipconfig

Windows 2000 IP Configuration

Ethernet adapter Local Area Connection:

        Connection-specific DNS Suffix  . :
        IP Address. . . . . . . . . . . . : 10.0.2.15
        Subnet Mask . . . . . . . . . . . : 255.255.255.0
        Default Gateway . . . . . . . . . : 10.0.2.2
```

I can use the mount as `\\10.0.2.2` - but obviously I'd need to change the image and I'm not sure whether this is purely dynamic, or whether the IP address/range is consistent (presumably not?) or can it be configured as an argument to qemu (and/or if the batch script could be parameterised?) ?

**Comment by hectorm** [comment]
I don't know if it is related to the kernel version but I have found that since I upgraded the base image to Ubuntu 22.04 this image has this problem if running on Ubuntu 20.04.

Could you confirm if the problem is fixed in the v13 version I just released?

**Comment by mkst** [comment]
Sorry it took so long to re-test -- pulling latest looks to have solved it, samba mounted successfully - thanks (I'll close the ticket)!
