### ISSUE TITLE
RDP :port 3389 and vnc not working for me .

### ISSUE THREAD

**Issue by Dawingwan** [hectorm/docker-qemu-win2000#9]
Hi 
firstly ,thank you made this amazing docker image free for us.

My environment is centos7.9 I can see the docker and  qemu-win2000 is running,  I can use terminal go inside and see dir c:/ see programes. However I opened port:3389 vnc 6080 for vps , and  I still cant use RDP port: 3389 and the vnc sames not working to qemu-win2000 too.

--
{
"AppArmorProfile" :
"",
"Args" :
[ … ],
"Config" :
{ … },
"Created" :
"2022-09-26T04:07:21.699020294Z",
"Driver" :
"overlay2",
"ExecIDs" :
[ … ],
"GraphDriver" :
{ … },
"HostConfig" :
{ … },
"HostnamePath" :
"/var/lib/docker/containers/a3f2d1b8e83559b7e5310d8aa6217d12ad8197ce0c3d9fbf4f191e0867bf296c/hostname",
"HostsPath" :
"/var/lib/docker/containers/a3f2d1b8e83559b7e5310d8aa6217d12ad8197ce0c3d9fbf4f191e0867bf296c/hosts",
"Id" :
"a3f2d1b8e83559b7e5310d8aa6217d12ad8197ce0c3d9fbf4f191e0867bf296c",
"Image" :
"sha256:2bbc17c255c5c77868c486a96ea71b6644f37852eed59291f0e5da0fab27d6c6",
"LogPath" :
"/var/lib/docker/containers/a3f2d1b8e83559b7e5310d8aa6217d12ad8197ce0c3d9fbf4f191e0867bf296c/a3f2d1b8e83559b7e5310d8aa6217d12ad8197ce0c3d9fbf4f191e0867bf296c-json.log",
"MountLabel" :
"",
"Mounts" :
[ ],
"Name" :
"/qemu-win2000",
"NetworkSettings" :
{ … },
"Path" :
"/usr/bin/catatonit",
"Platform" :
"linux",
"ProcessLabel" :
"",
"ResolvConfPath" :
"/var/lib/docker/containers/a3f2d1b8e83559b7e5310d8aa6217d12ad8197ce0c3d9fbf4f191e0867bf296c/resolv.conf",
"RestartCount" :
0,
"State" :
{ … }
I dont know what is problem ,  could you please give me any idea ?
thanks

best regards

**Comment by hectorm** [comment]
Could you provide the way you are running the container? The `docker run` command for example.

**Comment by Dawingwan** [comment]
Hi Hectorm
I use this default command :

docker run --detach \
  --name qemu-win2000 \
  --device /dev/kvm \
  --publish 127.0.0.1:3389:3389/tcp \
  --publish 127.0.0.1:5900:5900/tcp \
  --publish 127.0.0.1:6080:6080/tcp \
  docker.io/hectorm/qemu-win2000:latest

to start container.

I can provid vps ssh information to you if you woud like help. 

thanks

**Comment by hectorm** [comment]
You cannot connect to the services outside the VPS because the ports are being published only on localhost.

In order to connect you can do a SSH tunnel or publish the ports on all interfaces. But be aware that it is **not** safe to make these ports publicly accessible, if you don't have any kind of firewall in front of your VPS you are putting your system at risk.
